export const PROJECTS = [
  {
    id: 'pricing-revamping',
    isPasswordProtected: true,
    title: 'Pricing Service Revamping',
    tags: ['System design', '0 to 1'],
    description: 'Design and launch pricing portal from sratch.  Streamline the Affirm’s pricing workflow and expand pricng capacity.',
    timeline: 'Oct 2019 - Jan 2020',
    role: 'Being the only designer on the team, I conducted user research, helped project roadmap planning, designed the end to end experience and support engineer  implementation',
    homeTopImage: require('@/assets/pricing-revamping/home-top.png'),
    homeBottomImage: require('@/assets/pricing-revamping/home-bottom.png'),
    heroImage: require('@/assets/pricing-revamping/hero.png'),
  },
  {
    id: 'investor-analytics-dashboard',
    isPasswordProtected: true,
    title: 'Investor Analytics Dashboard',
    tags: ['Data visulaization'],
    description: 'Led the design and research of Affirm’s portfolios analytics dashboard that deliver critique insights on loan performance of Affirm’s counterparties.',
    timeline: 'Jun 2019 - Sep 2020',
    role: 'Being the led designer on this project, I structure the research plan conducted several user research, designed the end to end experience and support engineer implementation',
    homeTopImage: require('@/assets/investor-analytics-dashboard/home-top.png'),
    homeBottomImage: require('@/assets/investor-analytics-dashboard/home-bottom.png'),
    heroImage: require('@/assets/investor-analytics-dashboard/hero.png'),
  },
  {
    id: 'loan-application-form',
    title: 'Loan Application Form',
    tags: ['Desktop & Mobile', 'A/B testing'],
    description: 'Led the design of 3 around A/B testing of Credible’s loan pre-qualification form.',
    timeline: '2019',
    role: 'Led designer',
    homeTopImage: require('@/assets/loan-application-form/home-top.png'),
    homeBottomImage: require('@/assets/loan-application-form/home-bottom.png'),
    heroImage: require('@/assets/loan-application-form/hero.png'),
  },
];