export const PROJECTS = [
  {
    id: 'pricing-revamping',
    title: 'Pricing Revamping',
    tags: ['System design', '0 to 1'],
    description: 'Design and launch pricing portal from sratch.  Streamline the Affirm’s pricing workflow and expand pricng capacity.',
    timeline: 'Oct 2019 - Jan 2020',
    role: 'Being the only designer on the team, I conducted user research, helped project roadmap planning, designed the end to end experience and support engineer  implementation',
    homeTopImage: require('@/assets/pricing-revamping/home-top.png'),
    homeBottomImage: require('@/assets/pricing-revamping/home-bottom.png'),
    heroImage: require('@/assets/pricing-revamping/hero.png'),
  },
  {
    id: 'loan-application-form',
    title: 'Loan Application Form',
    tags: ['Desktop & Mobile', 'A/B testing & Iteration'],
    description: 'Led the design of 3 around A/B testing of Credible’s loan pre-qualification form.',
    timeline: '2019',
    role: 'Led designer',
    homeTopImage: require('@/assets/loan-application-form/home-top.png'),
    homeBottomImage: '',
    heroImage: require('@/assets/loan-application-form/hero.png'),
  },
  {
    id: 'pricing-revamping-3',
    title: 'Pricing Revamping',
    tags: ['System design', '0 to 1'],
    description: 'Design and launch pricing portal from sratch.  Streamline the Affirm’s pricing workflow and expand pricng capacity.',
    timeline: 'Oct 2019 - Jan 2020',
    role: 'Being the only designer on the team, I conducted user research, helped project roadmap planning, designed the end to end experience and support engineer  implementation',
    homeTopImage: require('@/assets/pricing-revamping/home-top.png'),
    homeBottomImage: require('@/assets/pricing-revamping/home-bottom.png'),
    heroImage: require('@/assets/pricing-revamping/hero.png'),
  },
  {
    id: 'pricing-revamping-4',
    title: 'Pricing Revamping',
    tags: ['System design', '0 to 1'],
    description: 'Design and launch pricing portal from sratch.  Streamline the Affirm’s pricing workflow and expand pricng capacity.',
    timeline: 'Oct 2019 - Jan 2020',
    role: 'Being the only designer on the team, I conducted user research, helped project roadmap planning, designed the end to end experience and support engineer  implementation',
    homeTopImage: require('@/assets/credible-mobile/home-top.png'),
    homeBottomImage: require('@/assets/credible-mobile/home-bottom.png'),
    heroImage: require('@/assets/pricing-revamping/hero.png'),
  },
];